AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infrastructure for user info agent self-managed memory'

Parameters:
  MemoryId:
    Type: String
    Description: AgentCore Memory ID (use 'placeholder' initially, update after creating memory)
  ModelId:
    Type: String
    Default: anthropic.claude-3-haiku-20240307-v1:0
    Description: Bedrock model ID for extraction
  MemoryExecutionRoleArn:
    Type: String
    Description: ARN of the memory execution role (create manually)

Resources:
  # S3 Bucket for memory events
  MemoryEventsBucket:
    Type: AWS::S3::Bucket

  # SNS Topic for notifications
  MemoryEventsTopic:
    Type: AWS::SNS::Topic

  # SQS Queue for processing
  MemoryEventsQueue:
    Type: AWS::SQS::Queue

  # Lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: MemoryProcessingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${MemoryEventsBucket}/*'
              - Effect: Allow
                Action:
                  - bedrock-runtime:InvokeModel
                Resource: '*'
              - Effect: Allow
                Action:
                  - bedrock-agentcore:BatchCreateMemoryRecords
                Resource: '*'

  # Lambda function
  MemoryProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-memory-processor'
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          AGENTCORE_MEMORY_ID: !Ref MemoryId
          MY_BEDROCK_MODEL_ID: !Ref ModelId
      Code:
        ZipFile: |
          import json
          import os
          import boto3
          from datetime import datetime, timezone

          REGION = os.getenv("AWS_REGION", "us-east-1")
          MEMORY_ID = os.environ["AGENTCORE_MEMORY_ID"]
          MODEL_ID = os.environ["MY_BEDROCK_MODEL_ID"]

          s3 = boto3.client("s3", region_name=REGION)
          bedrock = boto3.client("bedrock-runtime", region_name=REGION)
          agentcore = boto3.client("bedrock-agentcore", region_name=REGION)

          EXTRACTION_SYSTEM = """You extract durable user memory for an assistant.
          Return ONLY valid JSON:
          {
            "facts":[{"key":"...", "value":"...", "confidence":0.0-1.0}],
            "preferences":[{"key":"...", "value":"...", "confidence":0.0-1.0}]
          }
          Rules:
          - Do NOT store secrets or highly sensitive identifiers (SSNs, passwords, full DOB, etc).
          - Prefer stable preferences and long-lived facts.
          """

          def invoke_model(user_text: str) -> dict:
              body = {
                  "anthropic_version": "bedrock-2023-05-31",
                  "max_tokens": 200,
                  "messages": [
                      {"role": "user", "content": f"{EXTRACTION_SYSTEM}\n\nText: {user_text}"}
                  ]
              }
              
              resp = bedrock.invoke_model(
                  modelId=MODEL_ID,
                  body=json.dumps(body)
              )
              result = json.loads(resp['body'].read())
              content = result['content'][0]['text']
              return json.loads(content)

          def handler(event, context):
              try:
                  record = event["Records"][0]
                  msg = json.loads(record["Sns"]["Message"])
                  
                  bucket = msg["s3"]["bucket"]
                  key = msg["s3"]["key"]
                  
                  obj = s3.get_object(Bucket=bucket, Key=key)
                  delivered = json.loads(obj["Body"].read())
                  
                  actor_id = delivered.get("actorId")
                  session_id = delivered.get("sessionId")
                  
                  messages = delivered.get("messages", [])
                  transcript = "\n".join(
                      f'{m.get("role","").upper()}: {m.get("content","")}' for m in messages
                  )
                  
                  extracted = invoke_model(transcript)
                  now = datetime.now(timezone.utc).isoformat()
                  
                  records = []
                  for f in extracted.get("facts", []):
                      records.append({
                          "namespace": f"/facts/{actor_id}",
                          "content": {"text": f'{f["key"]}: {f["value"]}'},
                          "metadata": {
                              "type": "fact",
                              "key": f.get("key"),
                              "confidence": f.get("confidence", 0.7),
                              "sourceSessionId": session_id,
                              "createdAt": now,
                          },
                      })
                  
                  if records:
                      agentcore.batch_create_memory_records(
                          memoryId=MEMORY_ID,
                          actorId=actor_id,
                          sessionId=session_id,
                          records=records,
                      )
                  
                  return {"ok": True, "stored": len(records)}
              except Exception as e:
                  print(f"Error: {str(e)}")
                  return {"ok": False, "error": str(e)}

  # SNS subscription to Lambda
  LambdaSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref MemoryEventsTopic
      Endpoint: !GetAtt MemoryProcessorFunction.Arn

  # Lambda permission for SNS
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MemoryProcessorFunction
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref MemoryEventsTopic

Outputs:
  MemoryEventsBucket:
    Description: S3 bucket for memory events
    Value: !Ref MemoryEventsBucket

  MemoryEventsTopicArn:
    Description: SNS topic ARN for memory events
    Value: !Ref MemoryEventsTopic

  MemoryEventsQueueArn:
    Description: SQS queue ARN for memory events
    Value: !GetAtt MemoryEventsQueue.Arn

  LambdaFunctionArn:
    Description: Lambda function ARN for processing
    Value: !GetAtt MemoryProcessorFunction.Arn